name: Wymer
favicon: null
layout_spectrum: 0.75544
typography_spectrum: 0.74522
title: Wymer @TheGrid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-67360421-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6748776659369469
  lightness: 0.07345922943204641
  saturation: 0.44620846305042505
  rhythmicContrast: 0.38758467114530504
purpose: []
